//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_WEB_API_SP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Newempreg
    {
        public int Empid { get; set; }
        public string Empname { get; set; }
        public string Email { get; set; }
        public string Location { get; set; }
        public Nullable<int> Salary { get; set; }
    }
}
